### ISSUE TITLE
Macchiato Theme

### ISSUE THREAD

**Issue by wrinkledeth** [catppuccin/zsh-syntax-highlighting#4]
Hello kind humans, would you able to add catppuccin machiatto to the list?

**Comment by hyperreal64** [comment]
Thank you for your input. I will add themes for Latte, Frappe, and Macchaito. It's just a matter of changing the color values.

**Comment by hyperreal64** [comment]
@wrinkledeth I've added themes for Latte, Frappe, and Macchiato. Please let me know if they are acceptable, and then I will close this issue. :-)

**Comment by wrinkledeth** [comment]
@hyperreal64  This is perfect, thanks so much! 

Have a wonderful day :)
